### ISSUE TITLE
install

### ISSUE THREAD

**Issue by brezzz1** [MAGOWARE/backoffice-administration#70]
Ive been battling to get this installed all day, wouldn't an install script with user inputs be easier?

**Comment by dmatos61** [comment]
It’s not designed to be easy.

**Comment by brezzz1** [comment]
What so you made it hard on purpose?

**Comment by brezzz1** [comment]
2019-10-09T14:24:45.991Z - info: Initializing Sequelize...
2019-10-09T14:24:46.257Z - info: Finished Connecting to Database
2019-10-09T14:24:46.258Z - info: Initializing Stack...
2019-10-09T14:24:46.351Z - error:
{ message: 'Address already in use',
stack: 'Error: Address already in use\n at Function.parseData (/root/backoffice-administration/node_modules/redis-server/RedisServer.js:167:22)\n at Socket.dataListener (/root/backoffice-administration/node_modules/redis-server/RedisServer.js:237:38)\n at emitOne (events.js:121:20)\n at Socket.emit (events.js:211:7)\n at addChunk (_stream_readable.js:263:12)\n at readableAddChunk (_stream_readable.js:250:11)\n at Socket.Readable.push (_stream_readable.js:208:10)\n at Pipe.onread (net.js:607:20)',
code: -1 }

Can anybody help with this please? I have already changed the magoware port to several different ones but I still get this error.

Thanks

**Comment by wanman** [comment]
That's a shame. You waste people's time and resources with broke stuff like
this.

**Comment by wanman** [comment]
That's what I  saying too. Someone needs to learn to code

**Comment by dmatos61** [comment]
I agree ,

**Comment by eduardhasanaj2** [comment]
Hi
We are really sorry for the inconvenience.
This problem is encountered due to the redis service which was not stopped gratefully during last shutdown.
We have embedded the redis in magoware to ease the installation process but sometimes the shutdown process is not correct in Linux. However in Windows systems we have not seen any problem.
To resolve this problem please find the redis process and kill it.
Supposing the redis is running on 6379 use following command to find the process id
`sudo netstat -tlnp` | grep "6379"
You will get the pid in this like in red circle in following image
![image](https://user-images.githubusercontent.com/23219826/66740848-7b137300-ee74-11e9-84e6-4e7da2b9c795.png)
Then you will kill the process using the id in red rectangle like in above image:
`sudo kill 12975`
I am closing this but if the steps above do not fix the problem we can reopen.

**Comment by krloswiguel** [comment]
No habrá una guía detallada de instalación
