### ISSUE TITLE
we provide custom white label apks

### ISSUE THREAD

**Issue by customapk** [MAGOWARE/backoffice-administration#74]
we provide custom white label apks

if u are looking for custom apk for magoware backoffice just contact us unlockdominicana@gmail.com
portal url inside and encrypted custom logos and all img available for phone tablets stb box fire tv android smart tv .

**Comment by irisstaro** [comment]
Hello @customapk 
Magoware does not provide the source code of end-users applications and is the owner of it. For any custom app you are interested please feel free to contact us at info@magoware.tv

Please note also that is not possible to advertise on our repository due to violation of privacy policy as stated below: 
"2. GitHub Repositories
GitHub repositories are intended to host Content. You may include static images, links, and promotional text in the README documents associated with your repositories, but they must be related to the project you are hosting on GitHub.
You may not advertise in other Users' repositories, such as by posting monetized or excessive bulk content in issues."

Regards
